language: cpp
sudo: false
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - clang-5.0
      - clang-tools-5.0
      - ninja-build

env:
  matrix:
    - CALI_TRAVIS_TESTNAME=clang-5
      CALI_CC=clang-5.0
      CALI_CXX=clang++-5.0
      WITH_MPI=Off
      FAIL_ON_FIND=On
      WITH_GOTCHA=On
    # Build test with gcc-6

script:
  - mkdir build-${CALI_TRAVIS_TESTNAME}
  - cd build-${CALI_TRAVIS_TESTNAME}
  - CMAKE_OPTS="-DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=On"
  - CMAKE_OPTS="${CMAKE_OPTS} -DCMAKE_C_COMPILER=${CALI_CC} -DCMAKE_CXX_COMPILER=${CALI_CXX}"
  - if [[ -n "${COVERAGE}" ]] ; then CMAKE_OPTS="${CMAKE_OPTS} -DCMAKE_C_FLAGS=-coverage -DCMAKE_CXX_FLAGS=-coverage"; fi
  - cmake -GNinja -DLAMMPS_INTERNAL_CI_DISABLE_OPENMP=On -DBUILD_OMP=Off -DPKG_KOKKOS=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ${CMAKE_OPTS} ../cmake
  - checker=stl-in-kokkos ninja -j4 check_global
